/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import MUESTREO.InstanciaEnGrises;
import MUESTREO.InstanciaImagenBinarizada;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Roberto Cruz Leija
 */
public class BinarizacionInternalFrame extends javax.swing.JInternalFrame {

    private Image imagenReferencia;
    private InstanciaImagenBinarizada binarizacion;
    /**
     * Creates new form BinarizacionInternalFrame
     */
    public BinarizacionInternalFrame(Image imagenReferencia) {
        initComponents();
        this.imagenReferencia = imagenReferencia;
        InstanciaEnGrises grises = new InstanciaEnGrises(imagenReferencia);
        
        this.jLabelImagenBin.setIcon(new ImageIcon(grises.generaImagenGrises()));
        this.binarizacion = new InstanciaImagenBinarizada(grises.getImagenGrises());
        grises.graficarHistograma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagenBin = new javax.swing.JLabel();
        jSliderUmbralI = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jLabelUmbralI = new javax.swing.JLabel();
        jSliderUmbralS = new javax.swing.JSlider();
        jLabelUmbralS = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jSliderUmbralI.setMaximum(255);
        jSliderUmbralI.setSnapToTicks(true);
        jSliderUmbralI.setValue(10);
        jSliderUmbralI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderUmbralIStateChanged(evt);
            }
        });

        jButton1.setText("Aplicar");

        jLabelUmbralI.setText("Umbral I: 10");

        jSliderUmbralS.setMaximum(255);
        jSliderUmbralS.setSnapToTicks(true);
        jSliderUmbralS.setValue(245);
        jSliderUmbralS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderUmbralSStateChanged(evt);
            }
        });

        jLabelUmbralS.setText("Umbral S: 245");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenBin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderUmbralS, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUmbralI)
                        .addGap(336, 336, 336)
                        .addComponent(jLabelUmbralS)
                        .addGap(12, 12, 12))
                    .addComponent(jSliderUmbralI, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagenBin, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUmbralI)
                            .addComponent(jLabelUmbralS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderUmbralI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderUmbralS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderUmbralIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderUmbralIStateChanged
       int valorI = jSliderUmbralI.getValue();
       int valorS = jSliderUmbralS.getValue();
       jLabelUmbralI.setText("UmbralI: "+valorI);
       jLabelUmbralS.setText("UmbralS: "+valorS);
       Image resultado = this.binarizacion.generarImagenBinarizada(valorI,valorS);
       jLabelImagenBin.setIcon(new ImageIcon(resultado));
       
    }//GEN-LAST:event_jSliderUmbralIStateChanged

    private void jSliderUmbralSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderUmbralSStateChanged
       int valorI = jSliderUmbralI.getValue();
       int valorS = jSliderUmbralS.getValue();
       jLabelUmbralI.setText("UmbralI: "+valorI);
       jLabelUmbralS.setText("UmbralS: "+valorS);
       Image resultado = this.binarizacion.generarImagenBinarizada(valorI,valorS);
       jLabelImagenBin.setIcon(new ImageIcon(resultado));
       
    }//GEN-LAST:event_jSliderUmbralSStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelImagenBin;
    private javax.swing.JLabel jLabelUmbralI;
    private javax.swing.JLabel jLabelUmbralS;
    private javax.swing.JSlider jSliderUmbralI;
    private javax.swing.JSlider jSliderUmbralS;
    // End of variables declaration//GEN-END:variables
}
