/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ajustesespaciales.ConvolucionEspacial;
import ajustesespaciales.Iluminacion;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Roberto Cruz Leija
 */
public class ConvolucionJInternalFrame extends javax.swing.JInternalFrame {

    private Image imagenReferencia;
   
    /**
     * Creates new form BinarizacionInternalFrame
     */
    public ConvolucionJInternalFrame(Image imagenReferencia) {
        initComponents();
        this.imagenReferencia = imagenReferencia;
        
        this.jLabelImagenBin.setIcon(new ImageIcon(imagenReferencia));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagenBin = new javax.swing.JLabel();
        jButtonConvolucionar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jButtonConvolucionar.setText("3x3");
        jButtonConvolucionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvolucionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenBin, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConvolucionar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagenBin, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addGap(68, 68, 68)
                .addComponent(jButtonConvolucionar)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConvolucionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvolucionarActionPerformed
       
        ConvolucionEspacial ce = new ConvolucionEspacial(imagenReferencia);
        //jLabelImagenBin.setIcon(new ImageIcon(ce.convolucionar3x3(new int[][]{(1,1,1),(1,1,1),(1,1,1)});
        this.imagenReferencia = ce.convolucionar3x3(new int [][]{{1,1,1},{1,1,1},{1,1,1}},0,9);
        this.jLabelImagenBin.setIcon(new ImageIcon(this.imagenReferencia));
    }//GEN-LAST:event_jButtonConvolucionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvolucionar;
    private javax.swing.JLabel jLabelImagenBin;
    // End of variables declaration//GEN-END:variables
}
