/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import MUESTREO.InstanciaEnGrises;
import MUESTREO.InstanciaImagenBinarizada;
import ajustesespaciales.Iluminacion;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Roberto Cruz Leija
 */
public class IluminacionJInternalFrame extends javax.swing.JInternalFrame {

    private Image imagenReferencia;
   
    /**
     * Creates new form BinarizacionInternalFrame
     */
    public IluminacionJInternalFrame(Image imagenReferencia) {
        initComponents();
        this.imagenReferencia = imagenReferencia;
        
        this.jLabelImagenBin.setIcon(new ImageIcon(imagenReferencia));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagenBin = new javax.swing.JLabel();
        jSliderAlpha = new javax.swing.JSlider();
        jLabelUmbralI = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jSliderAlpha.setMaximum(255);
        jSliderAlpha.setMinimum(-255);
        jSliderAlpha.setSnapToTicks(true);
        jSliderAlpha.setValue(0);
        jSliderAlpha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAlphaStateChanged(evt);
            }
        });

        jLabelUmbralI.setText("Alpha: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenBin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelUmbralI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jSliderAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagenBin, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUmbralI)
                .addGap(29, 29, 29)
                .addComponent(jSliderAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderAlphaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAlphaStateChanged
       int valorI = jSliderAlpha.getValue();
       jLabelUmbralI.setText("Alpha: "+valorI);
       
       Image resultado = Iluminacion.ajustarBrillo(valorI, imagenReferencia);
       jLabelImagenBin.setIcon(new ImageIcon(resultado));
       
    }//GEN-LAST:event_jSliderAlphaStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagenBin;
    private javax.swing.JLabel jLabelUmbralI;
    private javax.swing.JSlider jSliderAlpha;
    // End of variables declaration//GEN-END:variables
}
