/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import MUESTREO.InstanciaEnGrises;
import MUESTREO.InstanciaImagenBinarizada;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Roberto Cruz Leija
 */
public class JInternalFrameImagen extends javax.swing.JInternalFrame {

    private Image imagenOriginal;
    /**
     * Creates new form JInternalFrameImagen
     */
    public JInternalFrameImagen(Image imagenOriginal) {
        initComponents();
        this.imagenOriginal = imagenOriginal;
        
        this.jLabelImagen.setIcon(new ImageIcon(this.getImagenOriginal()));
        // re dimensionar el tamaño del internalframe
        setSize(imagenOriginal.getWidth(null), imagenOriginal.getHeight(null));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagen = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Imagen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 822, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 553, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagen;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the imagenOriginal
     */
    public Image getImagenOriginal() {
        return imagenOriginal;
    }

    /**
     * @param imagenOriginal the imagenOriginal to set
     */
    public void setImagenOriginal(Image imagenOriginal) {
        this.imagenOriginal = imagenOriginal;
        // modificar el label con la imagen
        this.jLabelImagen.setIcon(new ImageIcon(this.getImagenOriginal()));
        // re dimensionar el tamaño del internalframe
        setSize(imagenOriginal.getWidth(null), imagenOriginal.getHeight(null));
    }
}
